In [ ]:
import pandas as pd
import sys, warnings

warnings.filterwarnings('ignore', category=UserWarning)

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [2]:
raw_data = pd.read_csv('../data/raw/data.dsv', sep=';')

In [3]:
sys.path.append('../src')

from data_pipeline import cleaning_fe_pipeline

In [4]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5320605 entries, 0 to 5320604
Data columns (total 16 columns):
 #   Column              Dtype
---  ------              -----
 0   ANNEE               float64
 1   MOIS                float64
 2   ID                  int64
 3   NUM_REGISTRO        int64
 4   DATE_DOMICILIATION  object
 5   DATE_ENREG_DO       object
 6   DEVISE              object
 7   FRET                float64
 8   FOB                 float64
 9   ASSURANCE           float64
 10  FRAIS_ACCESSOIRE    float64
 11  CODE_SH             int64
 12  QUANTITE_DOMICILE   float64
 13  DATE_IMPUTATION     object
 14  DATE_ENREG_IMP      object
 15  QTE_IMPUTE          float64
dtypes: float64(8), int64(3), object(5)
memory usage: 649.5+ MB

In [5]:
raw_data_sample = raw_data.head(100000)
processed_sample = cleaning_fe_pipeline.fit_transform(raw_data_sample)
processed_sample.describe()

[_drop_unnecessary_columns] exécuté en 0.005s | Lignes restantes: 100000
[_filter_valid_currencies] exécuté en 0.018s | Lignes restantes: 97269
[_set_datatypes] exécuté en 9.093s | Lignes restantes: 97269
[_clean_quantities] exécuté en 0.173s | Lignes restantes: 97269
[_filter_quantity] exécuté en 0.015s | Lignes restantes: 86394
[_clean_null_date] exécuté en 0.015s | Lignes restantes: 86393
[_optimize_memory] exécuté en 0.008s | Lignes restantes: 86393
[_delai_extracting] exécuté en 0.013s | Lignes restantes: 62700
[_strategic_grouping] exécuté en 0.001s | Lignes restantes: 62700
[_temporal_engineering] exécuté en 0.004s | Lignes restantes: 62700
[_flags_creation] exécuté en 0.002s | Lignes restantes: 62700
[_unify_currency_to_eur] exécuté en 0.014s | Lignes restantes: 62700

,ANNEE,MOIS,FRET,FOB,ASSURANCE,FRAIS_ACCESSOIRE,QUANTITE_DOMICILE,QTE_IMPUTE,DELAI_ENREGISTREMENT,TRIMESTRE,MOIS_SIN,MOIS_COS,A_UNE_ASSURANCE,A_FRAIS_ACCESSOIRE
count,62700.00000,62700.00000,62700.00000,62700.00000,62700.00000,62700.00000,62700.00000,62700.00000,62700.00000,62700.00000,62700.00000,62700.00000,62700.00000,62700.00000
mean,2019.17603,6.60440,13519.68750,311453.53125,73.18103,1.07046,135843.96875,57714.66797,9.21892,2.53105,-0.00124,0.02410,0.01646,0.00188
std,2.46734,3.49130,221687.35938,3262256.00000,3990.48682,64.03938,933726.00000,552881.87500,42.72566,1.13866,0.70332,0.71047,0.12723,0.04334
min,2015.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00400,0.00100,0.00000,1.00000,-1.00000,-1.00000,0.00000,0.00000
25%,2017.00000,4.00000,0.00000,4430.84021,0.00000,0.00000,215.00000,129.00000,0.00000,2.00000,-0.50000,-0.50000,0.00000,0.00000
50%,2019.00000,7.00000,27.00000,15659.70996,0.00000,0.00000,4318.00000,2764.85999,0.00000,3.00000,-0.00000,0.00000,0.00000,0.00000
75%,2021.00000,10.00000,1317.49368,44991.55273,0.00000,0.00000,22000.00000,18000.00000,0.00000,4.00000,0.50000,0.86603,0.00000,0.00000
max,2024.00000,12.00000,14953148.00000,117963992.00000,478431.00000,10731.82031,20000000.00000,20000000.00000,360.00000,4.00000,1.00000,1.00000,1.00000,1.00000

In [6]:
processed_data = cleaning_fe_pipeline.fit_transform(raw_data)

[_drop_unnecessary_columns] exécuté en 0.223s | Lignes restantes: 5320605
[_filter_valid_currencies] exécuté en 0.709s | Lignes restantes: 5175529
[_set_datatypes] exécuté en 582.154s | Lignes restantes: 5175529
[_clean_quantities] exécuté en 9.720s | Lignes restantes: 5175529
[_filter_quantity] exécuté en 0.899s | Lignes restantes: 4597990
[_clean_null_date] exécuté en 0.827s | Lignes restantes: 4597966
[_optimize_memory] exécuté en 0.303s | Lignes restantes: 4597966
[_delai_extracting] exécuté en 0.773s | Lignes restantes: 3332655
[_strategic_grouping] exécuté en 0.043s | Lignes restantes: 3332655
[_temporal_engineering] exécuté en 0.307s | Lignes restantes: 3332655
[_flags_creation] exécuté en 0.027s | Lignes restantes: 3332655
[_unify_currency_to_eur] exécuté en 0.796s | Lignes restantes: 3332655

In [7]:
processed_data.describe()

,ANNEE,MOIS,FRET,FOB,ASSURANCE,FRAIS_ACCESSOIRE,QUANTITE_DOMICILE,QTE_IMPUTE,DELAI_ENREGISTREMENT,TRIMESTRE,MOIS_SIN,MOIS_COS,A_UNE_ASSURANCE,A_FRAIS_ACCESSOIRE
count,3332655.00000,3332655.00000,3332655.00000,3332655.00000,3332653.00000,3332655.00000,3332655.00000,3332655.00000,3332655.00000,3332655.00000,3332655.00000,3332655.00000,3332655.00000,3332655.00000
mean,2019.17331,6.60138,14300.64355,314167.12500,75.76111,1.68909,131958.04688,58199.90625,9.25140,2.53041,-0.00150,0.02113,0.01635,0.00153
std,2.46756,3.48522,251101.28125,3656671.00000,5027.88721,300.22324,904881.12500,545283.56250,42.73548,1.13658,0.70383,0.71006,0.12681,0.03907
min,2014.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00100,0.00100,0.00000,1.00000,-1.00000,-1.00000,0.00000,0.00000
25%,2017.00000,4.00000,0.00000,4410.00000,0.00000,0.00000,209.39999,124.00000,0.00000,2.00000,-0.50000,-0.50000,0.00000,0.00000
50%,2019.00000,7.00000,33.93200,15541.40039,0.00000,0.00000,4350.00000,2703.69995,0.00000,3.00000,-0.00000,0.00000,0.00000,0.00000
75%,2021.00000,10.00000,1342.00000,44998.81445,0.00000,0.00000,22080.00000,18024.00000,0.00000,4.00000,0.50000,0.86603,0.00000,0.00000
max,2024.00000,12.00000,14953148.00000,203891120.00000,3048725.00000,285000.00000,20000000.00000,20000000.00000,365.00000,4.00000,1.00000,1.00000,1.00000,1.00000

In [12]:
output_path = '../data/processed/cleaned_data.csv'
processed_data.to_csv(output_path, index=False, sep=',')

print(f"Données traitées et exportées avec succès vers : {output_path}")

Données traitées et exportées avec succès vers : ../data/processed/cleaned_data.csv